-- DO NOT MODIFY: this file is generated by scripts/generate-lua-colors.ts
local dogwaterColors = {
  ansi0Color = "#000910",
  ansi1Color = "#EF5B5B",
  ansi10Color = "#23E971",
  ansi11Color = "#FFE9BC",
  ansi12Color = "#70DBC6",
  ansi13Color = "#00ABFF",
  ansi14Color = "#83E9AB",
  ansi15Color = "#A6A6A6",
  ansi2Color = "#23E971",
  ansi3Color = "#FFBA4A",
  ansi4Color = "#47A3A0",
  ansi5Color = "#006EAD",
  ansi6Color = "#66B485",
  ansi7Color = "#666666",
  ansi8Color = "#485663",
  ansi9Color = "#FF5B53",
  backgroundColor = "#00151C",
  badgeColor = "#FF2600",
  boldColor = "#21FCDB",
  cursorColor = "#52FADE",
  cursorGuideColor = "#B3ECFF",
  cursorTextColor = "#021A18",
  foregroundColor = "#FFFFFF",
  linkColor = "#005CBB",
  selectedTextColor = "#56FCE1",
  selectionColor = "#526868"
}

return dogwaterColors
