-- DO NOT MODIFY: this file is generated by scripts/generate-palette.ts

local dogwater_palette = {
  ansi_0_color = "#000910",
  ansi_1_color = "#EF5B5B",
  ansi_2_color = "#23E971",
  ansi_3_color = "#FFBA4A",
  ansi_4_color = "#47A3A0",
  ansi_5_color = "#006EAD",
  ansi_6_color = "#66B485",
  ansi_7_color = "#666666",
  ansi_8_color = "#485663",
  ansi_9_color = "#FF5B53",
  ansi_10_color = "#23E971",
  ansi_11_color = "#FFE9BC",
  ansi_12_color = "#70DBC6",
  ansi_13_color = "#00ABFF",
  ansi_14_color = "#83E9AB",
  ansi_15_color = "#A6A6A6",
  background_color = "#00151C",
  badge_color = "#FF2600",
  bold_color = "#21FCDB",
  cursor_color = "#52FADE",
  cursor_guide_color = "#B3ECFF",
  cursor_text_color = "#021A18",
  foreground_color = "#FFFFFF",
  link_color = "#3265FF",
  selected_text_color = "#56FCE1",
  selection_color = "#526868"
}

return dogwater_palette
